# -*- coding: utf-8 -*-
"""WORD2VEC - Assignment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDo0-mcAOeL-9rj9SEmd8Y9GLi9kFa4h
"""

import numpy as np
import re
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

import pandas as pd

file_path = "/content/bbc_news_text_complexity_summarization.csv"

# Read CSV safely, skip bad lines
df = pd.read_csv(file_path, engine='python', on_bad_lines='skip')

print("Columns in dataset:", df.columns.tolist())

# Pick the first column that looks like text
possible_text_cols = [c for c in df.columns if 'text' in c.lower() or 'article' in c.lower()]
if not possible_text_cols:
    raise ValueError("No text column found!")
TEXT_COL = possible_text_cols[0]
print(f"Using column for training: {TEXT_COL}")

# Combine all text into one string
text_data = ' '.join(df[TEXT_COL].astype(str).tolist())
print("Total characters in corpus:", len(text_data))

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    return words

words = preprocess(corpus)
print("Total Words:", len(words))
print("Sample:", words[:10])

vocab = sorted(set(words))
vocab_size = len(vocab)

word2idx = {w: idx for idx, w in enumerate(vocab)}
idx2word = {idx: w for w, idx in word2idx.items()}

print(f"Vocabulary Size: {vocab_size}")

def generate_training_data(words, window_size=2):
    data = []
    for i, target_word in enumerate(words):
        target_idx = word2idx[target_word]
        for j in range(max(0, i - window_size), min(len(words), i + window_size + 1)):
            if i != j:
                context_idx = word2idx[words[j]]
                data.append((target_idx, context_idx))
    return np.array(data)

window_size = 2
training_data = generate_training_data(words, window_size)
print(f"Training samples: {len(training_data)}")

embedding_dim = 10
W1 = np.random.uniform(-1, 1, (vocab_size, embedding_dim))
W2 = np.random.uniform(-1, 1, (embedding_dim, vocab_size))

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

def forward_pass(target_idx):
    h = W1[target_idx].reshape(embedding_dim, 1)
    u = np.dot(W2.T, h)
    y_pred = softmax(u)
    return y_pred, h

epochs = 2000
learning_rate = 0.01

for epoch in range(epochs):
    loss = 0
    for target, context in training_data:
        y_pred, h = forward_pass(target)

        # One-hot for true context word
        y_true = np.zeros((vocab_size, 1))
        y_true[context] = 1

        # Compute error
        e = y_pred - y_true

        # Backpropagation
        dW2 = np.dot(h, e.T)
        dW1 = np.outer(e, h.T) # Corrected backpropagation for W1

        # Update weights
        W1[target, :] -= learning_rate * dW1[target, :] # Corrected update for W1
        W2 -= learning_rate * dW2

        # Compute loss
        loss += -np.log(y_pred[context] + 1e-9)

    if (epoch + 1) % 200 == 0:
        print(f"Epoch {epoch+1}/{epochs} - Loss: {loss[0]:.4f}")

print("\n✅ Training Complete!")

np.save("embeddings.npy", W1)
print("Saved embeddings to embeddings.npy")

"""## Visualizing Word Embeddings
Now that the Word2Vec model is trained, let's visualize the learned word embeddings. We'll use PCA (Principal Component Analysis) to reduce the dimensionality of the embeddings to 2 components for plotting.
"""

# Reduce dimensionality using PCA
pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(W1)

# Create a scatter plot
plt.figure(figsize=(10, 8))
for i, word in enumerate(vocab):
    x, y = embeddings_2d[i, :]
    plt.scatter(x, y)
    plt.annotate(word, xy=(x, y), xytext=(5, 2), textcoords='offset points', ha='right', va='bottom')

plt.title('Word Embeddings Visualization (PCA)')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.grid(True)
plt.show()